### ISSUE TITLE
Migrating from tmuxinator : same program with different arguments

### ISSUE THREAD

**Issue by aphecetche** [tmux-plugins/tmux-resurrect#144]
Hi,

I'm trying to use tmux-resurrect to handle my full tmux workflow (following https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/migrating_from_tmuxinator.md). 

There is one thing though that I don't see clearly how I can translate from tmuxinator to resurrect : I have a couple of windows of a tmux session that gets the same program executed, but with different parameters (see the mux "file" below). How can that work with resurrect ?

Thanks

```
name: ali
attach: false
#post: tmux -CC attach -t ali 
windows:
  - reco-2016:
      root: ~/alicesw/aliroot/reco-2016
      pre:  MYPARAM='-m aliroot=reco-2016' bash --init-file ~/Scripts/bash_profile.old 
      layout: main-horizontal
      panes:
        - cd src
        - cd build
  - tc-17: 
      root: ~/alicesw/aliroot/tc-17
      pre:  MYPARAM='-m aliroot=tc-17' bash --init-file ~/Scripts/bash_profile.old 
      layout: main-horizontal
      panes:
        - cd src
        - cd build
  - muonhlt:
      root: ~/alicesw/aliroot/feature-muonhlt
      pre:  MYPARAM='-m aliroot=feature-muonhlt' bash --init-file ~/Scripts/bash_profile.old 
      layout: main-horizontal
      panes:
        - cd src
        - cd build
  - master:
      root: ~/alicesw/aliroot/master
      pre:  MYPARAM='-m aliroot=master' bash --init-file ~/Scripts/bash_profile.old 
      layout: main-horizontal
      panes:
        - cd src
        - cd build
  - bugfix:
      root: ~/alicesw/aliroot/bugfix
      pre:  MYPARAM='-m aliroot=bugfix' bash --init-file ~/Scripts/bash_profile.old 
      layout: main-horizontal
      panes:
        - cd src
        - cd build
```
